entry: src/index.js
target: es2020
engines:
  firefox: "48"
  chrome: "50"
#bundle: true
#define:
#  __SPECIAL__: false
#external:
#  - fsevents
#  - react
#format: esm # esm, iife, cjs
#minify: true
sourcemap: linked # inline, linked

